plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mycompany.myapphtk'
    compileSdk 34

    defaultConfig {
        applicationId "com.mycompany.myapphtk"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}

dependencies {
}
